### ISSUE TITLE
Ck editor initializing is so slow.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ckeditor/ckeditor5-vue#82] opened 2019-07-20 23:16 UTC
Comment.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-20 23:17
Using browser: mozilla.
![изображение](https://user-images.githubusercontent.com/9306996/61585109-56ee1180-ab65-11e9-8054-6169fd134de2.png)
So, i have more than one component's which render new ckeditor.
I must wait 3 second's on every initializing.
![изображение](https://user-images.githubusercontent.com/9306996/61585117-6e2cff00-ab65-11e9-8803-19c4e4453f03.png)
Same with classic editor and other official builds.

![изображение](https://user-images.githubusercontent.com/9306996/61585125-b3e9c780-ab65-11e9-9d78-e78ac15561e9.png)
![изображение](https://user-images.githubusercontent.com/9306996/61585129-c6fc9780-ab65-11e9-8aa9-6585b4ad5393.png)
![изображение](https://user-images.githubusercontent.com/9306996/61585132-d085ff80-ab65-11e9-9d28-143641bd6ab4.png)
![изображение](https://user-images.githubusercontent.com/9306996/61585133-da0f6780-ab65-11e9-9d57-b0c12e566320.png)
![изображение](https://user-images.githubusercontent.com/9306996/61585136-e4316600-ab65-11e9-95b9-2d78d7ca3b1b.png)


As you can see ckeditor promises takes too much time.
https://dropmefiles.com/IKCcD profile
[profile.zip](https://github.com/ckeditor/ckeditor5-vue/files/3414061/profile.zip)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-20 23:18
If it's wrong repo, just move issue to other. Thank's.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-21 15:08
Maybe you can give a suggestion how i can workaround without dom blocking(page freezing) since ckeditor initializing)?

**Comment by Mgsy** [comment] 2019-07-22 12:06
@oleq, can you take a look at this one?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:23
Some workaround can be - using v-if to render ckeditor after initializing.
![изображение](https://user-images.githubusercontent.com/9306996/61635620-0a115480-aca5-11e9-9679-1f4694725ff7.png)


So, but now we can't do it, because if we gonna use v-if wrapper on ckeditor - ckeditor will not initialize at all.
So, maybe you can add some 'ref for this and make initializing programmaticaly? something like this.editor.init({parent_element: this.$refs.blablabla, onReady: ()=> this.onReady}); or something like that. Then we could work without dom blocking, component gonna render when it's ready at all.

**Comment by oleq** [comment] 2019-07-22 13:34
What's the version of `ckeditor5-vue`?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:41
Same with stable.
Everything is latest.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:42
Seem's like the most time taken by document editor initializing.
So then vue editor waiting for document editor promise resolve, and take +500ms to initialize vue component after promise resolved.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:46
Can confirm this on latest chrome too. Lol.

What 'bout programmaticaly init and destroy?

**Comment by oleq** [comment] 2019-07-22 13:46
Can you share the editor data you're using to initialize it?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:52
Nothing at all.
https://github.com/ckeditor/ckeditor5-vue/issues/82#issuecomment-513789193
https://github.com/ckeditor/ckeditor5-vue/issues/82#issuecomment-513505949
Check screenshots.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 13:53
Also check profile.
Then you can see that this is not data issue, this is document editor initializing is slow. As i said in https://github.com/ckeditor/ckeditor5-vue/issues/82#issuecomment-513796522.

**Comment by oleq** [comment] 2019-07-22 14:35
I cannot reproduce it. 

In an empty directory, I called:

```
yarn add vue @ckeditor/ckeditor5-vue @ckeditor/ckeditor5-build-decoupled-document
```

Then I used the following `index.html`.

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<h1>Hello world!</h1>
		
		<div id="app">
			<ckeditor :editor="editor" v-model="editorData" @ready="onReady"></ckeditor>
		</div>

		<script src="node_modules/vue/dist/vue.min.js"></script>
		<script src="node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js"></script>
		<script src="node_modules/@ckeditor/ckeditor5-vue/dist/ckeditor.js"></script>

		<script>
			Vue.use( CKEditor );

			const app = new Vue( {
				el: '#app',
				data: {
					editor: DecoupledEditor,
					editorData: '<p>Content of the editor.</p>',
				},
				methods: {
					onReady( editor ) {
						// Insert the toolbar before the editable area.
						editor.ui.getEditableElement().parentElement.insertBefore(
							editor.ui.view.toolbar.element,
							editor.ui.getEditableElement()
						);
					}
				}
			} );
		</script>
		<style>
			.ck.ck-editor__editable_inline {
				border: 1px solid #ccc;
			}
		</style>
	</body>
</html>
```

I cannot say its blazingly fast (because it's still 0.5MB JS in the CKEditor build), but it's nothing like 3s of waiting. Can you confirm using this minimal sample?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 14:46
`npm i @ckeditor/ckeditor5-vue @ckeditor/ckeditor5-build-decoupled-document```

```js

import Vue from 'vue';
import App from './App';
import CKEditor from '@ckeditor/ckeditor5-vue';

Vue.use( CKEditor );

const v = new Vue({
    render: h => h(App)
}).$mount('#app');
```
```js


<template>
    <div id="app" >
      <div @click="changeState">click here</div>
      <editorCompabcd v-if="tryToRender"/>
    </div>
</template>

<script>

    const editorComp= () => import(/* webpackChunkName: "editorComp" */'@/components/editorComp');


    export default{
        name:'App',
        components: {
            'editorCompabcd':editorComp
        },
        data() {
            return {
                tryToRender:false,
            };
        },
      methods: {
            changeState()  { this.tryToRender=!this.tryToRender; }
    }
}
```
```js
<template>
    <!-- <div v-if="isReady"> -->
        <ckeditor :editor="editor" v-model="editorData" @ready="onReady" @destroy="onEditorDestroy"></ckeditor>
    <!-- </div> -->
    
</template>

<script>
    import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
    export default {
        data() {
            return {
                isReady:false,
                editorData: '<p>Content of the editor.</p>',
                editor: DecoupledEditor,
            };
        },
        methods: {
            onReady( editor )  {
                console.log('on ready');
                console.log(editor===this.editor);
                console.log(editor.ui.getEditableElement());
                this.isReady=true;
                // Insert the toolbar before the editable area.
                editor.ui.getEditableElement().parentElement.insertBefore(
                    editor.ui.view.toolbar.element,
                    editor.ui.getEditableElement()
                );
            },
            onEditorDestroy()  {
                console.log('onEditorDestroy');
            }
        },
        destroyed(){
            console.log('on real destroyed')
        }
    }
</script>
<style lang="scss" >
</style>
```

**Comment by oleq** [comment] 2019-07-22 14:48
I mean, do you experience the lag when using the sample I provided?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 14:50
So, without conditions i can't how fast page loading is.
But at all you can check my example. It's the same, but with conditions, click on div after page full loading and you gonna get it.

**Comment by oleq** [comment] 2019-07-22 15:15
It takes around .6s on my machine (i7 Macbook Pro)

![image](https://user-images.githubusercontent.com/1099479/61643878-08935c80-aca4-11e9-8b58-c775cbb5a7b8.png)

It could be that it takes more than 1s on low–end hardware but it's far from 3s like you mentioned.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-22 15:17
Very strange.

**Comment by Mgsy** [comment] 2019-08-05 10:58
I'm closing this issue as we're not able to reproduce the problem. If you'll have some more information about it, feel free to comment - we'll check it.

**Closed by Mgsy** 2019-08-05 10:58 UTC
Labels: pending:feedback

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-10 15:41
@oleq i tested some another wysiwyg component's.
Froala first instance load - 0.7s.
Each next instance on page loading take ~0.6s.

Scrumpy - first instance load - 0.5s.
Each next instance on page loading take 0.5s.

I tested this with full plugin's list enabled.

But ckeditor decoupled loading take's too much time on notebook's for example. But there not too much plugins like in froala, which loading too faster.

![изображение](https://user-images.githubusercontent.com/9306996/62823836-dab87e00-bba6-11e9-9201-f994c4909f75.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-10 15:43
So, maybe you should take some test's and detect which one function loading takes too much time?
Coz this is very bad now.
Only Bold, Italic and text highliting plugins enabled by default.

**Comment by oleq** [comment] 2019-08-12 11:31
See https://github.com/ckeditor/ckeditor5-vue/issues/82#issuecomment-513797975

Without the content you load into the editor it's hard for us to test or relate to your issue.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-12 11:53
I said, it's empty.
Im using your example. xD.
https://github.com/ckeditor/ckeditor5-vue/issues/82#issuecomment-513818501

It's not related to data rendering at all, it's some js/timeouts/promises problem.

**Comment by Reinmar** [comment] 2019-08-12 12:00
Could you provide a sample, with all the code and dependencies on which we could reproduce this (ideally, a repository)? Just to be sure we're looking at the exact same thing. Right now, we don't see any major issue (although, the performance could, as always, be better).

Also, please share a screenshot of a timeline recorded on this demo.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-12 12:32
[test123.zip](https://github.com/ckeditor/ckeditor5-vue/files/3492297/test123.zip)

[profile.zip](https://github.com/ckeditor/ckeditor5-vue/files/3492302/profile.zip)

 As i said above im using empty project for testing.
And it takes near 3 seconds.

![GIF](https://user-images.githubusercontent.com/9306996/62865177-ce573100-bd1e-11e9-8c4a-3c44ef77cda2.gif)

**Comment by oleq** [comment] 2019-08-13 09:11
Thanks for the sample and the profile. I used the sample and here are the results:

## @afwn90cj93201nixr2e1re 's waterfall (~3,5s)

![image](https://user-images.githubusercontent.com/1099479/62929092-08c1dc00-bdba-11e9-902e-47e798598f71.png)

## My waterfall (~0,7s)

![image](https://user-images.githubusercontent.com/1099479/62929102-0cedf980-bdba-11e9-9d8d-f93cd35b9325.png)

----

I admit the difference is huge (it's around 5x) and TBH I'm not sure why. Could it be my hardware is 5 times faster in that case?

I tested in vanilla Firefox 68.0.1 (64-bit) (no add-ons etc.). Can you @afwn90cj93201nixr2e1re perform the same test in a clean Firefox installation? Just to make sure we're on the same page.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-13 14:41
it was clean. it's not related to browser or cpu, i mean more huge wyswigs initiazing take near 0.5s, but with ckeditor it take's near 3s.
Im on i9 8950HK, 2.9.

Maybe you can create some build with debug where we can find info about how many time takes each function?

**Comment by oleq** [comment] 2019-08-14 07:23
I ran the same test on another machine (Windows 10 this time) with a 10-year old CPU (Phenom II X4) and it took 1.5s to initialize the editor:

<img width="1435" alt="Untitled" src="https://user-images.githubusercontent.com/1099479/63001273-8d246580-be73-11e9-9d86-a5a1fbeedf72.png">

We know there's room for improvement (in various parts of the editor framework) but it's not nearly as bad as you suggest. And given your hardware configuration (Intel i9) this is even more disturbing because the editor should initialize way, way faster. 

So my guess it's either your OS (which one, BTW? Is it Linux?) or some other components (GPU?) causing some issues. Maybe you could try and run this demo on another machine and we could compare the results?

Anyway, this is the first time we see a performance issue this off the scale. There were some in the past but this is a new level. Unless we have more data (cases), it's hard for us to figure anything out because (as you saw) I tried to reproduce the problem but to no avail. Sorry 😔

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-14 07:28
What about this one? It's also can help to check which function initializing take's too much
> Maybe you can create some build with debug where we can find info about how many time takes each function?

7/8.1/10 win, 1060 6gb, 16gb RAM.

**Comment by oleq** [comment] 2019-08-14 10:38
> What about this one? It's also can help to check which function initializing take's too much in future

You can get this information straight, e.g. from Chrome dev tools (waterfall in the performance tab). There are plenty of functions that are used excessively and could be optimized but there's no single culprit here (like "one place to fix it all").

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-08-14 10:39
No, i can't. Coz it's minized. And here no options to get **each function** executing time.

**Comment by pshurygin** [comment] 2019-11-13 15:10
@oleq I wonder if there is any way to improve startup performance. I'm initializing ckeditor on user click and it takes about 400-800ms on my desktop i7 6700, which is a noticable delay. If i do the same with 4x throttling in dev tools, this time goes up to 3s+, which means it is pretty much unusable for people with low-spec laptops.

I'm talking here about initializing editor with just a few words without any initial formatting, so that it is not the input size problem. Also, i'm using custom build with just the plugins i need(pretty close to the official balloon build).

Maybe there is some way to pre-initialize ckeditor without content and without adding it to DOM? Or some other workaround to improve startup performance with initialize-on-click strategy.

**Comment by oleq** [comment] 2019-11-15 09:39
@pshurygin Do you experience this lag using the Vue adapter only or also when using the vanilla CKEditor API (`SomeEditor.create()`)? I'm trying to find the root of the problem.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 10:20
Can you create vue app with vanilla CKEditor initializing with checkbox, xD? We are not familiar with CKEditor like you.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 10:29
![изображение](https://user-images.githubusercontent.com/9306996/68936590-53396700-07b4-11ea-8196-cd9947e86205.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 10:34
xD, that's strange, with async await it takes 2 seconds.
![изображение](https://user-images.githubusercontent.com/9306996/68936963-f7231280-07b4-11ea-813a-15cfc5de9b06.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 10:44
![изображение](https://user-images.githubusercontent.com/9306996/68937783-7b29ca00-07b6-11ea-9ddc-75a7cfcac7b9.png)

**Comment by pshurygin** [comment] 2019-11-15 10:58
@oleq I'm using vanilla api BalloonEditor.create()

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 11:03
So, i can confirm that the problem is not in css files and svg boxes, xD: 
![изображение](https://user-images.githubusercontent.com/9306996/68939033-102dc280-07b9-11ea-9bcb-e05f1f3adfdb.png)


But browser throw attention that will-change require too much memory.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-15 11:15
First init:
![изображение](https://user-images.githubusercontent.com/9306996/68939716-b201df00-07ba-11ea-8d4d-8aee1814251a.png)


Second init:
![изображение](https://user-images.githubusercontent.com/9306996/68939746-c8a83600-07ba-11ea-9446-3a960c7404e3.png)


So, the most time seems taken by ui init.

**Comment by thorgeir** [comment] 2022-04-20 15:04
Hi, I just overcame a painfully slow initialization of ckeditor 5.
Turns out the sample code given on ckeditor.com for the webpack.config.js was to blame. 

What I changed was this section in webpack.config.js:


```
test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
use: [
	{
		loader: 'style-loader',
		options: {
			injectType: 'singletonStyleTag',
			attributes: {
				'data-cke': true
			}
		}
	},
	{
		loader: 'postcss-loader',
		options: styles.getPostCssConfig({
			themeImporter: {
				themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
			},
			minify: true
		})
	},
]
```

To 

```
test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
use: [
	{
		loader: MiniCssExtractPlugin.loader,
	},
	{
		loader: 'postcss-loader',
		options: styles.getPostCssConfig({
			themeImporter: {
				themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
			},
			minify: true
		})
	},
]
```			

Hope this helps someone.
