### ISSUE TITLE
vue Error in mounted hook: "TypeError: this.editor.create is not a function

### ISSUE THREAD

**Issue by starSmallDream** [ckeditor/ckeditor5-vue#177] opened 2021-02-03 04:41 UTC
![image](https://user-images.githubusercontent.com/28866025/106697756-5ff4e580-661a-11eb-8314-b9176e543295.png)
exception info:
     Invalid prop: type check failed for prop "editor". Expected Function, got Object 
    Error in mounted hook: "TypeError: this.editor.create is not a function"

vue page use:
   `<div class="b-cke-wrapper" >
            <ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @ready="onEditorReady"></ckeditor>
        </div>`

There is no problem with the next CKEDITOR version. However, this self-built version does not modify any content, but it will prompt that this.editor.create is not a function, which is strange; the solution is to rebuild the next version, and the code can basically be modified without modification. Normal use, I am very confused about the problematic build version.

[ckeditor5-balloon-block-build-01.zip](https://github.com/ckeditor/ckeditor5-vue/files/5916111/ckeditor5-balloon-block-build-01.zip)

**Comment by starSmallDream** [comment] 2021-02-03 04:42
If the above abnormal picture cannot be displayed, please see this text version of the stack information.

error info :

vue.esm.js?a026:628 [Vue warn]: Invalid prop: type check failed for prop "editor". Expected Function, got Object 

found in

---> <Ckeditor>
       <CKEditor5BalloonBlock> at src/components/CKEditor5BalloonBlock.vue
         <ElCol>
           <ElRow>
             <ElCard> at packages/card/src/main.vue
               <BookInfo> at src/views/book/BookInfo.vue
                 <Anonymous>
                   <ElMain> at packages/main/src/main.vue
                     <ElContainer> at packages/container/src/main.vue
                       <BaseLayout> at src/components/BaseLayout.vue
                         <App> at src/App.vue
                           <Root>
warn @ vue.esm.js?a026:628
assertProp @ vue.esm.js?a026:1714
validateProp @ vue.esm.js?a026:1641
loop @ vue.esm.js?a026:4674
initProps @ vue.esm.js?a026:4707
initState @ vue.esm.js?a026:4648
Vue._init @ vue.esm.js?a026:5015
VueComponent @ vue.esm.js?a026:5163
createComponentInstanceForVnode @ vue.esm.js?a026:3292
init @ vue.esm.js?a026:3123
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
merged @ vue.esm.js?a026:3310
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
merged @ vue.esm.js?a026:3310
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
merged @ vue.esm.js?a026:3310
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
patch @ vue.esm.js?a026:6527
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
eval @ main.js?56d7:109
./src/main.js @ app.js:2343
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:3232
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
Show 136 more frames
vue.esm.js?a026:628 [Vue warn]: Error in mounted hook: "TypeError: this.editor.create is not a function"

found in

---> <Ckeditor>
       <CKEditor5BalloonBlock> at src/components/CKEditor5BalloonBlock.vue
         <ElCol>
           <ElRow>
             <ElCard> at packages/card/src/main.vue
               <BookInfo> at src/views/book/BookInfo.vue
                 <Anonymous>
                   <ElMain> at packages/main/src/main.vue
                     <ElContainer> at packages/container/src/main.vue
                       <BaseLayout> at src/components/BaseLayout.vue
                         <App> at src/App.vue
                           <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
invokeWithErrorHandling @ vue.esm.js?a026:1871
callHook @ vue.esm.js?a026:4228
insert @ vue.esm.js?a026:3148
invokeInsertHook @ vue.esm.js?a026:6357
patch @ vue.esm.js?a026:6576
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
eval @ main.js?56d7:109
./src/main.js @ app.js:2343
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:3232
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
vue.esm.js?a026:1897 TypeError: this.editor.create is not a function
    at VueComponent.mounted (ckeditor.js?3730:5)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at callHook (vue.esm.js?a026:4228)
    at Object.insert (vue.esm.js?a026:3148)
    at invokeInsertHook (vue.esm.js?a026:6357)
    at Vue.patch [as __patch__] (vue.esm.js?a026:6576)
    at Vue._update (vue.esm.js?a026:3954)
    at Vue.updateComponent (vue.esm.js?a026:4075)
    at Watcher.get (vue.esm.js?a026:4488)
    at new Watcher (vue.esm.js?a026:4477)

**Comment by starSmallDream** [comment] 2021-02-03 04:51
If the above abnormal picture cannot be displayed, please see this text version of the stack information.


vue.esm.js?a026:628 [Vue warn]: Invalid prop: type check failed for prop "editor". Expected Function, got Object 

found in

---> <Ckeditor>


vue.esm.js?a026:628 [Vue warn]: Error in mounted hook: "TypeError: this.editor.create is not a function"

found in

---> <Ckeditor>
       <CKEditor5BalloonBlock> at src/components/CKEditor5BalloonBlock.vue

vue.esm.js?a026:1897 TypeError: this.editor.create is not a function
    at VueComponent.mounted (ckeditor.js?3730:5)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at callHook (vue.esm.js?a026:4228)
    at Object.insert (vue.esm.js?a026:3148)
    at invokeInsertHook (vue.esm.js?a026:6357)
    at Vue.patch [as __patch__] (vue.esm.js?a026:6576)
    at Vue._update (vue.esm.js?a026:3954)
    at Vue.updateComponent (vue.esm.js?a026:4075)
    at Watcher.get (vue.esm.js?a026:4488)
    at new Watcher (vue.esm.js?a026:4477)

**Comment by FilipTokarski** [comment] 2021-02-15 11:16
Hi, I checked the build you linked and was able to use it in Vue when I removed Watchdog and rebuilt it.
So it seems that the error is caused by the use of Watchdog, which is not supported in Vue at the moment. You can find more details  [in this ticket](https://github.com/ckeditor/ckeditor5/issues/4693).  
I'll close this as a duplicate.

**Closed by FilipTokarski** 2021-02-15 11:16 UTC
