### ISSUE TITLE
Using in Nuxt

### ISSUE THREAD

**Issue by Timibadass** [ckeditor/ckeditor5-vue#60] opened 2019-05-30 14:03 UTC

**Comment by Mgsy** [comment] 2019-05-31 08:08
Hi, can you describe what is this issue about?

**Comment by Mgsy** [comment] 2019-05-31 08:14
I see that you created an issue in other repository and found the solution, so I'm closing it as a duplicate of https://github.com/ckeditor/ckeditor5/issues/1785.

**Closed by Mgsy** 2019-05-31 08:14 UTC
Labels: pending:feedback
