### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by ThomasLaigneauDecathlon** [ckeditor/ckeditor5-vue#203] opened 2022-02-18 15:21 UTC
Hi,

When I update my project node version to Node 16, my Ckeditor is not working anymore. It's displaying good but any modification won't be taken.

I see this error in my chrome console :

<img width="1248" alt="Capture d’écran 2022-02-18 à 16 19 30" src="https://user-images.githubusercontent.com/86826718/154710599-550931bc-3293-41b6-8f42-6d8f2cd1c65a.png">

It seems to be related with the vue component and this.$_instance seems to be undefined.

Any idea ?

**Comment by O-Hooman** [comment] 2022-02-21 11:26
it also happens to me, try vue@3.2.30

**Comment by ThomasLaigneauDecathlon** [comment] 2022-02-21 12:14
I'm using Vue 3.2.31.

Should I downgrade to 3.2.30 ?

**Comment by ThomasLaigneauDecathlon** [comment] 2022-02-21 12:54
Still the same error after downgrade

**Comment by O-Hooman** [comment] 2022-02-22 08:26
@ThomasLaigneauDecathlon idk if this will help but try to delete the node_modules & package-lock and npm i vue@3.2.30 && npm install

**Comment by shoaibsharif** [comment] 2022-02-26 17:40
Thank @O-Hooman , downgrading to `3.2.30` is working. But is that vue issue?

**Comment by retosteffen** [comment] 2022-02-28 14:29
same problem for me when going from vue 3.2.30 to 3.2.31

**Comment by zcmk123** [comment] 2022-03-11 03:33
same problem here wat happen?

**Comment by FilipTokarski** [comment] 2022-03-11 11:52
Hi, thanks for the report. I can confirm I get this error also on node `14.15.4` and Vue `3.0.0`. The editor however seems to be working fine.

Error message:
```js
TypeError: Cannot read properties of undefined (reading 'model')
    at Proxy.$_setUpEditorEvents (ckeditor.js?3730:5:1)
    at eval (ckeditor.js?3730:5:1)
```

**Comment by ychongsaytc** [comment] 2022-03-11 14:53
Refer to Vue 3:
<https://github.com/vuejs/core/blob/v3.2.31/packages/runtime-core/src/componentPublicInstance.ts#L412`>

> Attempting to mutate public property "xxx". Properties starting with $ are reserved and readonly.

So, why do the CKEditor maintainers using “$“ as property prefix?

Source code: <https://github.com/ckeditor/ckeditor5-vue/blob/v2.0.1/src/ckeditor.js#L52>

**Comment by Varkoff** [comment] 2022-03-15 10:09
> it also happens to me, try vue@3.2.30 if you using Vue 3
I encountered the same error. Downgrading to vue@3.2.30 solved it for me. Thanks guys !

**Comment by psmyrek** [comment] 2022-03-16 08:30
Thank you for the hints. It looks like this bug is caused by the changes between 3.2.30 and 3.2.31 in Vue and maybe it will be fixed in the next version of Vue, according to the comment: https://github.com/vuejs/core/issues/5492#issuecomment-1054625160.

However, this issue can be fixed also in the CKEditor5 Vue component by using the `markRaw()` method to explicitly tell Vue to never convert the editor instance to a proxy.

**Closed** 2022-03-17 06:32 UTC
Labels: type:bug, squad:devops, status:in-progress

**Comment by pomek** [comment] 2022-03-17 06:35
A new version of the Vue integration is released. 👉  https://github.com/ckeditor/ckeditor5-vue/releases/tag/v3.0.0
