### ISSUE TITLE
ckeditor5-vue will result   Memory leaks

### ISSUE THREAD

**Issue by 505141222** [ckeditor/ckeditor5-vue#61] opened 2019-05-31 03:00 UTC
ckeditor5-vue will result   Memory leaks where ckeditor5 are created and destroyed frequently.the function destroy can't remove ckeditor totally. when ckeditor5 are created and destroyed frequently,I find the Memory rising all the time in Task Manager.

**Comment by jodator** [comment] 2019-05-31 07:40
Hi, we are aware of this: https://github.com/ckeditor/ckeditor5/issues/1731 and I don't think it is related to the vue integration only.

Unfortunately it looks like Chrome `74` introduced some changes that causes more leaks then in previous versions.

I'm closing this as duplicate of #1731 - please subscribe to that one to track it's progress.

**Closed by jodator** 2019-05-31 07:40 UTC
Labels: resolution:duplicate, type:bug
