### ISSUE TITLE
Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by owen-gxz** [ckeditor/ckeditor5-vue#83] opened 2019-07-23 09:51 UTC
error:
![image](https://user-images.githubusercontent.com/8510542/61702380-465eb680-ad72-11e9-9e56-c71c8642214e.png)
vue.config.js:
```
const path = require('path')
const webpack = require('webpack')
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' );
const { styles } = require( '@ckeditor/ckeditor5-dev-utils' )
const resolve = dir => {
  return path.join(__dirname, dir)
}

// 项目部署基础
// 默认情况下，我们假设你的应用将被部署在域的根目录下,
// 例如：https://www.my-app.com/
// 默认：'/'
// 如果您的应用程序部署在子路径中，则需要在这指定子路径
// 例如：https://www.foobar.com/my-app/
// 需要将它改为'/my-app/'
// iview-admin线上演示打包路径： https://file.iviewui.com/admin-dist/
const BASE_URL = process.env.NODE_ENV === 'production'
  ? '/'
  : '/'

module.exports = {
  // Project deployment base
  // By default we assume your app will be deployed at the root of a domain,
  // e.g. https://www.my-app.com/
  // If your app is deployed at a sub-path, you will need to specify that
  // sub-path here. For example, if your app is deployed at
  // https://www.foobar.com/my-app/
  // then change this to '/my-app/'
  baseUrl: BASE_URL,
  // tweak internal webpack configuration.
  // see https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md
  // 如果你不需要使用eslint，把lintOnSave设为false即可
  lintOnSave: true,
  chainWebpack: config => {
    config.resolve.alias
      .set('@', resolve('src')) // key,value自行定义，比如.set('@@', resolve('src/components'))
      .set('_c', resolve('src/components'));

    //  //todo ckeditor
    // (1.) To handle editor icons, get the default rule for *.svg files first:
    const svgRule = config.module.rule( 'svg' );

    // Then you can either:
    //
    // * clear all loaders for existing 'svg' rule:
    //
    //		svgRule.uses.clear();
    //
    // * or exclude ckeditor directory from node_modules:
    svgRule.exclude.add( path.join( __dirname, 'node_modules', '@ckeditor' ) );

    // Add an entry for *.svg files belonging to CKEditor. You can either:
    //
    // * modify the existing 'svg' rule:
    //
    //		svgRule.use( 'raw-loader' ).loader( 'raw-loader' );
    //
    // * or add a new one:
    config.module
      .rule( 'cke-svg' )
      .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
      .use( 'raw-loader' )
      .loader( 'raw-loader' );

    // (2.) Transpile the .css files imported by the editor using PostCSS.
    // Make sure only the CSS belonging to ckeditor5-* packages is processed this way.
    config.module
      .rule( 'cke-css' )
      .test( /ckeditor5-[^/\\]+[/\\].+\.css$/ )
      .use( 'postcss-loader' )
      .loader( 'postcss-loader' )
      .tap( () => {
        return styles.getPostCssConfig( {
          themeImporter: {
            themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' ),
          },
          minify: true
        } );
      } );
  },
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        'window.Quill': 'quill/dist/quill.js',
        'Quill': 'quill/dist/quill.js'
      }),
      new CKEditorWebpackPlugin( {
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'en'
      } )
    ]
  },
  // 设为false打包时不生成.map文件
  productionSourceMap: false,
  // 这里写你调用接口的基础路径，来解决跨域，如果设置了代理，那你本地开发环境的axios的baseUrl要写为 '' ，即空字符串
  // devServer: {
  //   proxy: 'localhost:3000'
  // }

  //todo ckeditor
  transpileDependencies: [
    /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/,
  ],
}

```
package.json:
```
 "@ckeditor/ckeditor5-basic-styles": "^11.1.3",
    "@ckeditor/ckeditor5-build-classic": "^12.3.1",
    "@ckeditor/ckeditor5-build-decoupled-document": "^12.3.1",
    "@ckeditor/ckeditor5-core": "^12.2.1",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.2",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.2",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.3",
    "@ckeditor/ckeditor5-essentials": "^11.0.4",
    "@ckeditor/ckeditor5-image": "^13.1.2",
    "@ckeditor/ckeditor5-link": "^11.1.1",
    "@ckeditor/ckeditor5-paragraph": "^11.0.4",
    "@ckeditor/ckeditor5-theme-lark": "^14.1.1",
    "@ckeditor/ckeditor5-ui": "^13.0.2",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
    "@fortawesome/fontawesome-free": "5.8.1",
```
ckeditor.vue
```
<template>
  <div class='editor'>
    <ckeditor :editor='editor' v-model='editorData' :config='editorConfig' />
  </div>
</template>

<script>
import CKEditor from '@ckeditor/ckeditor5-vue'
// import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'
// import ClassicEditor from '@ckeditor/ckeditor5-build-decoupled-document'
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import Image from '@ckeditor/ckeditor5-image/src/image'

export default {
  name: 'Editor',
  components: {
    ckeditor: CKEditor.component
  },
  data () {
    return {
      editor: ClassicEditor,
      editorData: '<p>Content of the editor.</p>',
      editorConfig: {
        plugins: [Image]
        // toolbar: ['image']
      }
    }
  }
}
</script>

```

**Comment by Mgsy** [comment] 2019-07-23 13:03
Hello, I've built the editor using your code and I've received different errors. Anyway, the most important issue I see here is that you import `Image` feature while importing a build. `ckeditor5-build-classic` already contains `Image` plugin, so importing it the way you did will cause modules duplication. 

Please, take a look at our [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) for a better understanding of how plugins work.

After removing following lines and builing a project, everything works fine for me:
```js
import Image from '@ckeditor/ckeditor5-image/src/image'

plugins: [Image]
```

**Comment by owen-gxz** [comment] 2019-07-24 02:59
yes! It's repeated.

I'm trying to modify editor.vue, but it was still incorrect
```
<template>
  <div class='editor'>
    <ckeditor :editor='editor' v-model='editorData' :config='editorConfig' />
  </div>
</template>

<script>
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'

import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials'
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold'
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic'
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link'
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph'

export default {
  name: 'Editor',
  components: {
    // ckeditor: CKEditor.component // ckeditor in main.js,  and vue.use(ckeditor)
  },
  data () {
    return {
      editor: ClassicEditor,
      editorData: '<p>Content of the editor.</p>',
      editorConfig: {
        plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin
        ],
        toolbar: {
          items: [
            'bold',
            'italic',
            'link',
            'undo',
            'redo'
          ]
        }
      }
    }
  }
}
</script>
```

error: 
![image](https://user-images.githubusercontent.com/8510542/61761595-bcf6c500-ae01-11e9-8391-c968eeb5c886.png)
error url: 
[It was not possible to load the plugin.](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load)

**Comment by Mgsy** [comment] 2019-07-25 07:25
As I wrote before, I've used your code and successfully built the editor. Can you follow steps from our [integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source) and see if the problem still exists?

**Comment by owen-gxz** [comment] 2019-07-25 07:35
if I used [using-es6-modules](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules) ,It's successfully.
but i used 
[using-the-editor-from-source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source) is error

**Comment by Krystus** [comment] 2019-07-25 19:06
@Mgsy the same error on my end. It have something in common with toolbar. Editor is semi working when I left only undo/redo toolbar options. But anyway toolbar never is visible. Error have something in common with ContextualBalloon.

![Screenshot 2019-07-25 at 21 04 03](https://user-images.githubusercontent.com/15039636/61901323-c8d8a900-af1f-11e9-8f7b-cf7a8225761a.jpg)

**Comment by Mgsy** [comment] 2019-07-26 06:49
@oleq, can you check if you're able to reproduce this issue?

**Comment by oleq** [comment] 2019-07-29 09:24
As for the errors in the `IconView` component, it looks like something's wrong with the way SVGs are processed by webpack.

These two are crucial:

```js
svgRule.exclude.add( path.join( __dirname, 'node_modules', '@ckeditor' ) );
```

```js
config.module
	.rule( 'cke-svg' )
	.test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
	.use( 'raw-loader' )
	.loader( 'raw-loader' );
```

Can you please make sure `path.join( __dirname, 'node_modules', '@ckeditor' )` actually points to the `@ckeditor` folder?

**Comment by owen-gxz** [comment] 2019-07-29 09:40
@oleq 
my vue.config.js:
```
const path = require('path')
const webpack = require('webpack')
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' );
const { styles } = require( '@ckeditor/ckeditor5-dev-utils' )
const resolve = dir => {
  return path.join(__dirname, dir)
}

// 项目部署基础
// 默认情况下，我们假设你的应用将被部署在域的根目录下,
// 例如：https://www.my-app.com/
// 默认：'/'
// 如果您的应用程序部署在子路径中，则需要在这指定子路径
// 例如：https://www.foobar.com/my-app/
// 需要将它改为'/my-app/'
// iview-admin线上演示打包路径： https://file.iviewui.com/admin-dist/
const BASE_URL = process.env.NODE_ENV === 'production'
  ? '/'
  : '/'

module.exports = {
  // Project deployment base
  // By default we assume your app will be deployed at the root of a domain,
  // e.g. https://www.my-app.com/
  // If your app is deployed at a sub-path, you will need to specify that
  // sub-path here. For example, if your app is deployed at
  // https://www.foobar.com/my-app/
  // then change this to '/my-app/'
  baseUrl: BASE_URL,
  // tweak internal webpack configuration.
  // see https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md
  // 如果你不需要使用eslint，把lintOnSave设为false即可
  lintOnSave: true,
  chainWebpack: config => {
    config.resolve.alias
      .set('@', resolve('src')) // key,value自行定义，比如.set('@@', resolve('src/components'))
      .set('_c', resolve('src/components'));

    //  //todo ckeditor
    // (1.) To handle editor icons, get the default rule for *.svg files first:
    const svgRule = config.module.rule( 'svg' );

    // Then you can either:
    //
    // * clear all loaders for existing 'svg' rule:
    //
    //		svgRule.uses.clear();
    //
    // * or exclude ckeditor directory from node_modules:
    svgRule.exclude.add( path.join( __dirname, 'node_modules', '@ckeditor' ) );

    // Add an entry for *.svg files belonging to CKEditor. You can either:
    //
    // * modify the existing 'svg' rule:
    //
    //		svgRule.use( 'raw-loader' ).loader( 'raw-loader' );
    //
    // * or add a new one:
    config.module
      .rule( 'cke-svg' )
      .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
      .use( 'raw-loader' )
      .loader( 'raw-loader' );

    // (2.) Transpile the .css files imported by the editor using PostCSS.
    // Make sure only the CSS belonging to ckeditor5-* packages is processed this way.
    config.module
      .rule( 'cke-css' )
      .test( /ckeditor5-[^/\\]+[/\\].+\.css$/ )
      .use( 'postcss-loader' )
      .loader( 'postcss-loader' )
      .tap( () => {
        return styles.getPostCssConfig( {
          themeImporter: {
            themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' ),
          },
          minify: true
        } );
      } );
  },
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        'window.Quill': 'quill/dist/quill.js',
        'Quill': 'quill/dist/quill.js'
      }),
      new CKEditorWebpackPlugin( {
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'en'
      } )
    ]
  },
  // 设为false打包时不生成.map文件
  productionSourceMap: false,
  // 这里写你调用接口的基础路径，来解决跨域，如果设置了代理，那你本地开发环境的axios的baseUrl要写为 '' ，即空字符串
  // devServer: {
  //   proxy: 'localhost:3000'
  // }

  //todo ckeditor
  transpileDependencies: [
    /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/,
  ],
}

```

**Comment by oleq** [comment] 2019-07-29 10:05
@owen-gxz I saw your config. But I don't know what your project looks like, what's the structure of folders, etc.. Hence my question:

> Can you please make sure `path.join( __dirname, 'node_modules', '@ckeditor' )` actually points to the `@ckeditor` folder?

?

**Comment by owen-gxz** [comment] 2019-07-30 02:09
ok!i used [iview-admin](https://github.com/iview/iview-admin),
I think it's a normal vue cli 3.0

**Comment by Mgsy** [comment] 2020-10-08 13:44
I'm closing it because of an insufficient amount of information about the issue.

**Closed by Mgsy** 2020-10-08 13:44 UTC
Labels: pending:feedback, squad:integrations
