### ISSUE TITLE
Load plugins

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5-vue#8] opened 2018-11-05 16:09 UTC
I'am not able to load plugin through my component.

```javascript
import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials'
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold'
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic'
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link'
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph'

export default {
  name: 'document',
  components: {},
  data () {
    return {
      editorData: '<p>Hello world!</p>',
      editorConfig: {
        language: 'fr',
        plugins: [
          EssentialsPlugin,
          BoldPlugin
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin
        ],
        //
        toolbar: {
          items: [
            'bold'
            'italic',
             'link',
            'undo',
            'redo'
          ]
        }
      }
    }
  }
}
```

This error raised

```console
CKEditorError: "model-selection-set-ranges-not-range: Selection range set to an object that is not an instance of model.Range. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-set-ranges-not-range
```

**Comment by Reinmar** [comment] 2018-11-05 16:12
I guess you're trying to use an existing editor build. That won't work. You need to use it with the editor integrated from source – e.g. `@ckeditor/ckeditor5-editor-classic`. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source

**Comment by kl3sk** [comment] 2018-11-05 16:20
That true, I installed this build and now (with all plugins enabled)

```console
TypeError: "svg is null"
```

**Comment by Reinmar** [comment] 2018-11-05 16:22
That's covered a bit earlier in the docs :) https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#configuring-vueconfigjs. In general, you have to go through the entire ["Integrating CKEditor 5 from source"](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source) section.

**Comment by kl3sk** [comment] 2018-11-05 16:23
My bad I've read it earlier ...

So I'am going to build my own editor.

**Comment by kl3sk** [comment] 2018-11-05 19:13
I think i have a conflict with ``css-loader`` used by ``vuetify``

**Comment by kl3sk** [comment] 2018-11-06 09:47
I did not achieve it in conjunction with Vuetify that seems to use `css-loader`. I don't know how to modify (I think vue.config.js) to make it working.

Does this component will allow pulugin customisation ?

**Comment by ggirodda** [comment] 2018-12-19 19:10
I have the same problem with nuxt. I follow the docs but I still have 'svg is null'. Here is my nuxt.config.js file:
```
const CKEditorWebpackPlugin = require("@ckeditor/ckeditor5-dev-webpack-plugin")
const CKEditorStyles = require("@ckeditor/ckeditor5-dev-utils").styles

module.exports = {
  // some config before
  build: {
    plugins: [
      // CKEditor needs its own plugin to be built using webpack.
      new CKEditorWebpackPlugin({
          // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
          language: "en"
      })
    ],
    // Various modules in the CKEditor source code import .css files.
    // These files must be transpiled using PostCSS in order to load properly.
    postcss: CKEditorStyles.getPostCssConfig({
        themeImporter: {
            themePath: require.resolve("@ckeditor/ckeditor5-theme-lark")
        },
        minify: true
    }),
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Vue CLI would normally use its own loader to load .svg files. The icons used by
      // CKEditor should be loaded using raw-loader instead.
      config.module.rules.push({
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ["file-loader","raw-loader"]
      })
    }
}
```
I don't know if the config is correct, I follow the following guides to interact with webpack from nuxt config:
https://nuxtjs.org/faq/webpack-plugins
https://nuxtjs.org/faq/postcss-plugins
https://nuxtjs.org/faq/extend-webpack

**Comment by jodator** [comment] 2018-12-20 09:23
@ggirodda please check updated vue guide for loading SVGs:https://github.com/ckeditor/ckeditor5/blob/bc613e17b68e17ac0487af30b75f7566c21f2186/docs/builds/guides/frameworks/vuejs.md#configuring-vueconfigjs (its only availble on master ATM). Does it solve your issue?

**Comment by ggirodda** [comment] 2018-12-20 14:11
@jodator Thank you for your answer, now it works. Here you can find a valid exemple for integration with nuxtjs:
```
const CKEditorWebpackPlugin = require("@ckeditor/ckeditor5-dev-webpack-plugin")
const CKEditorStyles = require("@ckeditor/ckeditor5-dev-utils").styles

module.exports = {
  // some config before
  build: {
    plugins: [
      // CKEditor needs its own plugin to be built using webpack.
      new CKEditorWebpackPlugin({
          // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
          language: "en"
      })
    ],
    // Various modules in the CKEditor source code import .css files.
    // These files must be transpiled using PostCSS in order to load properly.
    postcss: CKEditorStyles.getPostCssConfig({
        themeImporter: {
            themePath: require.resolve("@ckeditor/ckeditor5-theme-lark")
        },
        minify: true
    }),
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      const filesRuleIndex = config.module.rules.findIndex(item => {
        return `${item.test}` == "/\\.(png|jpe?g|gif|svg|webp)$/"
      })
      if (filesRuleIndex !== -1) {
        config.module.rules[filesRuleIndex].test = /\.(png|jpe?g|gif|webp)$/
        const svgRule = config.module.rules[filesRuleIndex]
        svgRule.test = /\.svg/
        svgRule.exclude = svgRule.exclude || []
        svgRule.exclude.push(__dirname + "/node_modules/@ckeditor")
        config.module.rules.push(svgRule)
      }
      // Vue CLI would normally use its own loader to load .svg files. The icons used by
      // CKEditor should be loaded using raw-loader instead.
      config.module.rules.push({
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ["raw-loader"]
      })
    }
}
```

**Comment by narisada014** [comment] 2018-12-26 09:30
@ggirodda 
In nuxt, how did you transplice a plugin library such as HeadingButtonsUI?

**Comment by iamKyun** [comment] 2019-12-05 15:47
@ggirodda  It works fine! But in my case, this line is still need to modify
`const filesRuleIndex = config.module.rules.findIndex(item => {
     return `${item.test}` == **"/\\.(png|jpe?g|gif|svg|webp)$/"**
})
`
to
`
const filesRuleIndex = config.module.rules.findIndex((item) => {
    return `${item.test}` === **'/\\.(png|jpe?g|gif|svg|webp)$/i'**
})
`

**Comment by iamKyun** [comment] 2019-12-05 15:52
> @ggirodda
> In nuxt, how did you transplice a plugin library such as HeadingButtonsUI?

https://nuxtjs.org/api/configuration-build/#transpile

**Comment by ggirodda** [comment] 2019-12-05 16:49
@iamKyun ok thank you, I updated my example

**Comment by trantinan2512** [comment] 2019-12-23 09:18
The price for adding plugins and configuring is so much I decided to build the custom editor. [Here's how to do it](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)

Aside from the issues in this thread, I also ran into [Some CKEditor 5 modules are duplicated](https://github.com/ckeditor/ckeditor5-vue/issues/83) and [Cannot read property 'getAttribute' of null](https://github.com/ckeditor/ckeditor5-vue/issues/72)

The custom build reduces my `nuxt.config.js` by a BUNCH, and makes the project much cleaner. For those who run into SSR failing, check [this](https://github.com/ckeditor/ckeditor5-vue/issues/71#issuecomment-543223817)

I have strong thoughts the repo is not very well compatible with nuxt, so this workaround is imo the most optimal way to go for now...

**Comment by Mgsy** [comment] 2020-01-14 11:49
Note for people using Nuxt.js - I've created a [feature request](https://github.com/ckeditor/ckeditor5/issues/6071) for Nuxt.js integration, so feel free to add 👍 to the first post to bump its popularity and join the discussion.

@kl3sk, did you manage to solve your issue? If not, could you provide some more information about your problem?

**Comment by yamenarahman** [comment] 2020-02-12 14:36
In my case I had to edit these lines:
```
return `${item.test}` === '/\\.(jpg|JPG|jpeg|png|gif|mp3|svg|ttf|woff2|woff|eot)$/gi';
```

```
svgRule.exclude.push(path.join(__dirname, '/node_modules/@ckeditor'));
```

But also still the same error exits
```
It was not possible to load the plugin.
Cannot read property 'getAttribute' of null.
```

@Mgsy @ggirodda @iamKyun Any advice?

**Comment by jeck5895** [comment] 2020-03-23 13:36
> The price for adding plugins and configuring is so much I decided to build the custom editor. And it just WORKS. [Here's how to do it](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)
> 
> Aside from the issues in this thread, I also ran into [Some CKEditor 5 modules are duplicated](https://github.com/ckeditor/ckeditor5-vue/issues/83) and [Cannot read property 'getAttribute' of null](https://github.com/ckeditor/ckeditor5-vue/issues/72)
> 
> The custom build reduces my `nuxt.config.js` by a BUNCH, and makes the project much cleaner. For those who run into SSR failing, check [this](https://github.com/ckeditor/ckeditor5-vue/issues/71#issuecomment-543223817)
> 
> I have strong thoughts the repo is not very well compatible with nuxt, so this workaround is imo the most optimal way to go for now...

I have custom build for my project. but the problem is it exceeds babel 500kb limit and won't compile. have you encountered the same?

**Comment by Mgsy** [comment] 2020-10-08 13:38
As the discussion seems to be focused around Nuxt.js, I'm closing it and all people interested in Nuxt.js integration, please refer to the [Nuxt.js feature request](https://app.zenhub.com/workspace/o/ckeditor/ckeditor5/issues/6071).

**Closed by Mgsy** 2020-10-08 13:38 UTC
Labels: pending:feedback, squad:integrations, type:question
