### ISSUE TITLE
Config prop is not reactive

### ISSUE THREAD

**Issue by rhysstubbs** [ckeditor/ckeditor5-vue#125] opened 2020-02-11 15:44 UTC
My issue is that when I am trying to insert/upload an image, the `ckfinder.uploadUrl` which is inside a computed property contains a null value as it's dynamically set using a template literal (e.g. `example.com/entity/${entity.id}/mediaUpload`. Maybe I should be setting the config elsewhere but I thought the computed property would be the way to go?

I have the follow in a template:

`<ckeditor
            :editor="editor"
            :config="editorConfig"
            v-model="editorData"
            @input="onEditorInput"
            @ready="onEditorReady"
          />
`

The prop `:config="editorConfig"` is pointing to a computed property. I am dynamically setting the `ckfinder.uploadUrl` (e.g. example.com/entity/{id}/upload).

Using Vue DevTools I can see the computed property is correct which leads me to believe that the component is only taking the config during it's load sequence? Meaning my url is likely to have a `null` or `undefined` value.

I'm already binding a function to `@ready`, should I also be setting the config here? Maybe I am doing something obviously wrong but some guidance would be great as I don't quite understand why the computed property isn't doing the trick.

**Comment by rhysstubbs** [comment] 2020-02-11 15:47
My bad, I have just discovered issue #99  detailing this exact issue. I will leave this here just in case someone else has some newer information on it.

**Comment by Mgsy** [comment] 2020-10-08 13:51
I'm closing it as a duplicate of https://github.com/ckeditor/ckeditor5-vue/issues/99.

**Closed by Mgsy** 2020-10-08 13:51 UTC
Labels: squad:integrations
