### ISSUE TITLE
V-model and tag-name not working as expected

### ISSUE THREAD

**Issue by gborcherds** [ckeditor/ckeditor5-vue#30] opened 2019-03-04 14:24 UTC
Hi there,

I've got a build going and the editor works in every instance except in setting an initial value and trying to change the tag-name. 

Here is my template

```javascript
<template>
    <v-layout wrap>
        <v-flex>
            <ckeditor tag-name="textarea" :editor="classEditor" v-model="value" :config="editorConfig"></ckeditor>
        </v-flex>
    </v-layout>

</template>
```

Here is my build of options

```javascript
<script>
  import states from './../../static/states'
  import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
  import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
  import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline'
  import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
  import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';

  export default {
    props: {},
    data () {
      return {
        yesNo: ['Yes', 'No'],
        stateOptions: states,
        classEditor : ClassicEditor,
        editorConfig : {
          plugins: [
            EssentialsPlugin,
            Underline,
            BoldPlugin,
            ItalicPlugin
          ],
          toolbar: [ 'bold', 'italic', 'underline']
        },
      }
    },
    methods: {}
  }
```

In my component I am setting the value of "value" to test. When I load the component, the value is there in dev tools, when I click on the editor and start typing, value changes to whatever I'm typing. But the editor won't show "test" when it first loads.

Second, I tried changing it to a textarea using tag-name and that isn't showing up. Any idea what would be going on here? Everything seems to be working except showing the initial value from v-model.

**Comment by gborcherds** [comment] 2019-03-04 14:28
I also just created a simple value to dynamically update the value to "Hello World" and when I update the value, it just makes the value go blank and clear the editor.

**Comment by oleq** [comment] 2019-03-05 15:16
I don't see `value` to meet `v-model="value"` in your component's `data`.

**Comment by gborcherds** [comment] 2019-03-05 15:30
The full file with the actual editor is below. It does have it. I have the configuration for the editor in a mixin because I use this editor in a lot of different places and so I extracted all the configuration to the mixin.

`javascript
<template>
    <v-layout wrap>
        <v-flex>
            <ckeditor tag-name="span" :editor="classEditor" v-model="value" :config="editorConfig"></ckeditor>
            <v-btn @click="showNow">Test</v-btn>
        </v-flex>
    </v-layout>

</template>

<script>
  export default {
    props: {
      option : Object
    },
    data () {
      return {
        value : 'test',
        show : false
      }
    },
    mounted() {

    },
    watch : {
      option : function(newOption, oldOption) {
//        this.value = newOption.value
//        console.log(this.value)
      }
    },
    methods: {
      showNow() {
        this.value = 'Hello World'
      }
    }
  }
</script>
`

**Comment by oleq** [comment] 2019-03-12 09:58
I used the following code

```html
<body>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.8/vue.min.js"></script>
	<script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>
	<script src="../dist/ckeditor.js"></script>

	<div id="app">
		<ckeditor tag-name="span" :editor="classEditor" v-model="value" :config="editorConfig"></ckeditor>
	</div>

	<script>
		Vue.use( CKEditor );

		const app = new Vue( {
			el: '#app',
			data () {
				return {
					classEditor: ClassicEditor,
					value: 'test',
					editorConfig : {
						toolbar: [ 'bold', 'italic' ]
					}
				}
			},
		} );
	</script>
</body>
```

and got both the initial data an the `<span>` as the data container

![image](https://user-images.githubusercontent.com/1099479/54191035-64a7d200-44b5-11e9-8f2d-e783af702282.png)

Maybe the problem is somewhere else? What do you exactly mean by 

> trying to change the tag-name

?

**Comment by gborcherds** [comment] 2019-03-12 18:58
I switched out the build from use the build I was doing to the basic one and it worked. So there was definitely something with my configuration. I'm just wondering what was missing from the custom build to the classic build that would allow this to work.

**Comment by oleq** [comment] 2019-03-18 11:47
@gborcherds Can you provide the configuration (building blocks) of your custom build?

**Comment by gborcherds** [comment] 2019-03-19 14:54
@oleq the building blocks are in the original issue description. I'm using Laravel Mix using webpack to perform the build, but the packages I was including are the ones from the original issue post.

**Comment by Flobbos** [comment] 2020-01-02 23:58
I have the exact same problem. I can't get the v-model filled with content, no matter how simple it is. The only way to show the content that's loaded into the v-model is by going into dev-tools and manually changing the editor content by adding a space or whatever and then it will show. Nothing else works. This is highly frustrating. 

```
<template>
    <div>
        <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
        <textarea :name="name" v-model="editorData" style="display: none;"></textarea>
    </div>
    
</template>

<script>
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
    import CKEditor from '@ckeditor/ckeditor5-vue';
    
    export default {
        components: {
            ckeditor: CKEditor.component
        },
        props: {
            content: {
                type: String,
                default: ''
            },
            name: {
                type: String,
                default: 'description'
            }
        },
        data() {
            return {
                editorData: this.content,
                editor: ClassicEditor,
                editorConfig: {
                    name: this.name,
                }
            };
        }
    }
</script>
<style lang="scss">
    
</style>

```

I also tried adding just a simple <p>Boo!</p> and it won't display. No idea what's going on.

**Comment by oleq** [comment] 2020-01-03 11:43
@Flobbos I created an [online sample](https://codesandbox.io/s/gracious-snowflake-t72ew) with your code and it just works. Am I missing something?

![image](https://user-images.githubusercontent.com/1099479/71721765-acbe2980-2e26-11ea-919d-8263ce52ca0c.png)

**Comment by Flobbos** [comment] 2020-01-03 11:51
I ended up removing CKEditor entirely and reinstalling the latest version. It was version 11.2.0 according to my package.json file. No idea why it suddenly refused to work after being fully functional for almost a year using that version.

**Comment by EduardoRomo** [comment] 2020-03-27 02:51
I had exactly the same issue. It was fixed updating @ckeditor/ckeditor5-vue from version "^1.0.0-beta.1" to "^1.0.1".

**Comment by Nyoijizai** [comment] 2020-08-21 02:05
the same problem.

why `v-model` not work? when I using CKEditor from source

```
"@ckeditor/ckeditor5-vue": "^1.0.1",
"@ckeditor/ckeditor5-editor-classic": "^21.0.0",

<template>
    <div id="app">
        <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

export default {
    data() {
        return {
            editor: ClassicEditor,
            editorData: "<p>Content of the editor.</p>",
            editorConfig: {},
        };
    },
};
</script>
```

**Comment by Nyoijizai** [comment] 2020-08-21 02:07
> I had exactly the same issue. It was fixed updating @ckeditor/ckeditor5-vue from version "^1.0.0-beta.1" to "^1.0.1". Same thing, it suddenly stopped working after months using the same version.

version "^1.0.1" can't work for now.I got a problem

**Comment by Mgsy** [comment] 2020-10-08 13:41
I'm closing this issue as we're unable to reproduce it. If you feel that we should investigate it, please open a new issue with a detailed description and steps to reproduce the problem.

**Closed by Mgsy** 2020-10-08 13:41 UTC
Labels: pending:feedback, squad:integrations, type:bug
